// --- Helper methods to calculate objective scores generated by an applicant in a certain team ---

/*
devPrefScore = sum(<applicant>.prefs.<team>)
For each team: score = feWeight*sum(<applicant>.feExperience) + beWeight*sum(<applicant>.feExperience) + …

permutationScore = A*devPrefScore + B*sum(<team>.score) + C*sum((<team>.score - avgTeamScore)2)
*/
